<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Images\Joints\default.png" />
	  <None Remove="Images\Joints\double_v.png" />
	  <None Remove="Images\Joints\single_u.png" />
	  <None Remove="Images\Joints\single_v.png" />
	  <None Remove="Images\Passes\default.png" />
	  <None Remove="Images\Passes\Passes.png" />
	  <None Remove="Images\Passes\single_v_pass.png" />
	  <None Remove="tessdata\eng.traineddata" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="tessdata\eng.traineddata">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\WeldAdminPro.Core\WeldAdminPro.Core.csproj" />
		<ProjectReference Include="..\WeldAdminPro.Data\WeldAdminPro.Data.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
		<PackageReference Include="Tesseract" Version="5.2.0" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Images\Joints\default.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Images\Joints\double_v.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Images\Joints\single_u.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Images\Joints\single_v.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Images\Passes\default.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Images\Passes\double_v_pass.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Images\Passes\single_v_pass.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>

</Project>