<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\WeldAdminPro.Core\WeldAdminPro.Core.csproj" />
		<ProjectReference Include="..\WeldAdminPro.Data\WeldAdminPro.Data.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
		<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.3" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.3" />
	</ItemGroup>

</Project>
