using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Linq;
using System.Windows;
using System.Windows.Input;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using WeldAdminPro.Core.Execution;
using WeldAdminPro.Core.Models;
using WeldAdminPro.Data.Repositories;
using WeldAdminPro.Data.Services;
using WeldAdminPro.Core.Events;

namespace WeldAdminPro.UI.ViewModels.Dashboard
{
	
	public partial class ProductionExecutionViewModel : ObservableObject
	{
		public Action? RefreshRequested;

		private readonly WorkOrderRepository _repository;
		private readonly WorkOrderExecutionService _executionService;
		private readonly WorkOrderMaterialRepository _materialRepo;
		private readonly StockRepository _stockRepo;

		public ICommand CancelWorkOrderCommand { get; }
		
		[ObservableProperty]
		private ObservableCollection<WorkOrder> readyWorkOrders = new();

		[ObservableProperty]
		private ObservableCollection<WorkOrder> runningWorkOrders = new();

		[ObservableProperty]
		private ObservableCollection<WorkOrder> completedToday = new();

		[ObservableProperty]
		private ObservableCollection<WorkOrderMaterialTrace> selectedWorkOrderMaterials = new();

		public ProductionControlTowerViewModel? ControlTower { get; set; }

		// =========================================================
		// CONSTRUCTOR
		// =========================================================

		public ProductionExecutionViewModel(WorkOrderExecutionService executionService)
		{
			_executionService = executionService;
			_repository = new WorkOrderRepository();

			_materialRepo = new WorkOrderMaterialRepository();
			_stockRepo = new StockRepository();

			CancelWorkOrderCommand = new RelayCommand<Guid>(CancelWorkOrder);
		}

		// =========================================================
		// LOAD DATA
		// =========================================================

		public void Load()
		{
            var all =
				_repository.GetAll().ToList();

            var active =
                all.Where(w =>
                    w.Status != WorkOrderStatus.Completed)
                .ToList();

            var engine = new BlockReasonEngine();
			var materialRepo = new WorkOrderMaterialRepository();
			var stockRepo = new StockRepository();

			foreach (var wo in all)
			{
				Debug.WriteLine($"WO: {wo.WorkOrderNumber} | Status: {wo.Status}");

				var materials = materialRepo.GetByWorkOrderId(wo.Id);

				wo.Type = materials.Any()
					? WorkOrderType.Production
					: WorkOrderType.Procurement;

				wo.MaterialRequirements = materials.Select(m =>
				{
					var stock = stockRepo.GetAll()
						.FirstOrDefault(s => s.ItemCode == m.ItemCode);

					return new MaterialRequirement
					{
						ItemCode = m.ItemCode,
						RequiredQuantity = m.RequiredQuantity
						// ❌ REMOVE AvailableQuantity
					};
				}).ToList();

				var result = engine.Evaluate(wo);

				wo.BlockReason = result.Reason;
				wo.BlockMessage = result.Message;
			}

            ReadyWorkOrders =
				new ObservableCollection<WorkOrder>(
					active.Where(w =>
					w.Status == WorkOrderStatus.Ready));

            RunningWorkOrders =
                new ObservableCollection<WorkOrder>(
                    active.Where(w =>
                        w.Status == WorkOrderStatus.InProduction));

            CompletedToday =
				new ObservableCollection<WorkOrder>(
					all.Where(w =>
					w.Status == WorkOrderStatus.Completed &&
					w.ActualEndTime?.Date == DateTime.Today));
        }

		// =========================================================
		// MATERIAL TRACE
		// =========================================================

		public void LoadMaterialTrace(WorkOrder workOrder)
		{
			var materials = _materialRepo.GetByWorkOrderId(workOrder.Id);

			SelectedWorkOrderMaterials.Clear();

			foreach (var m in materials)
			{
				if (string.IsNullOrWhiteSpace(m.ItemCode))
					continue;

				var stock = _stockRepo.GetAll()
					.FirstOrDefault(s => s.ItemCode == m.ItemCode);
                var reservationRepo =
					new ReservedMaterialRepository();

                double available =
                    reservationRepo
                        .GetAvailableQuantity(
                            m.ItemCode,
                            stock?.Quantity ?? 0);

                SelectedWorkOrderMaterials.Add(
					new WorkOrderMaterialTrace
					{
						ItemCode = m.ItemCode,
						Description =
						stock?.Description
						?? m.ItemCode,
						
						Quantity =
						(int)m.RequiredQuantity,
						
						AvailableQuantity =
						(int)available,
						
						UnitCost =
						stock?.AverageUnitCost ?? 0
					});
            }

			OnPropertyChanged(nameof(SelectedWorkOrderMaterials));
			OnPropertyChanged(nameof(TotalMaterialCost));
		}

		public decimal TotalMaterialCost =>
			SelectedWorkOrderMaterials.Sum(x => x.TotalCost);

		// =========================================================
		// COMMANDS (AUTO-GENERATED BY MVVM TOOLKIT)
		// =========================================================

		[RelayCommand]
		private void Start(Guid id)
		{
			Debug.WriteLine("🚀 START CLICKED");

			try
			{
				_executionService.StartWorkOrder(id);
			}
			catch (Exception ex)
			{
				Debug.WriteLine($"❌ START ERROR: {ex.Message}");
				return;
			}

			// ✅ CLEAN REFRESH
			RefreshRequested?.Invoke();

			Load();
			ControlTower?.Load();
		}

		[RelayCommand]
		private void PauseWorkOrder(Guid id)
		{
			_executionService.PauseWorkOrder(id);

			RefreshRequested?.Invoke();

			Load();
			ControlTower?.Load();
		}

		[RelayCommand]
		private void CompleteWorkOrder(Guid id)
		{
			_executionService.CompleteWorkOrder(id);

			RefreshRequested?.Invoke();

			Load();
			ControlTower?.Load();
		}
		private void CancelWorkOrder(Guid id)
		{
			try
			{
				_executionService.CancelWorkOrder(id);
				Load();
				ControlTower?.Load();
			}
			catch (Exception ex)
			{
				Debug.WriteLine(ex.Message);
			}
		}
	}
}